// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZPd9i1I5H5rDbVjLUf3TmCSR-USJvGSI',
    appId: '1:122177373861:web:cce07b22212fa8a6abef4c',
    messagingSenderId: '122177373861',
    projectId: 'live-imagesharing-matcher',
    authDomain: 'live-imagesharing-matcher.firebaseapp.com',
    storageBucket: 'live-imagesharing-matcher.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz4qmeD0z4vkpyG5IOBOwmSPdsCkyzDR4',
    appId: '1:122177373861:android:4c5222c5e28dc56cabef4c',
    messagingSenderId: '122177373861',
    projectId: 'live-imagesharing-matcher',
    storageBucket: 'live-imagesharing-matcher.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKGSb2FARA0xyYQemx6haCzvVM-4vHl6k',
    appId: '1:122177373861:ios:e7d9e415de6cc2beabef4c',
    messagingSenderId: '122177373861',
    projectId: 'live-imagesharing-matcher',
    storageBucket: 'live-imagesharing-matcher.appspot.com',
    iosBundleId: 'com.chilllabs.vistatest',
  );
}
